#!/bin/sh

NAME="NAME"
VERSION="VERSION"
DESCRIPTION="DESCRIPTION"

git grep -l NAME -- './*' ':(exclude)script/init-template' | xargs sed -i '' "s/NAME/$NAME/g"
git grep -l VERSION -- './*' ':(exclude)script/init-template' | xargs sed -i '' "s/VERSION/$VERSION/g"
git grep -l DESCRIPTION -- './*' ':(exclude)script/init-template' | xargs sed -i '' "s/DESCRIPTION/$DESCRIPTION/g"
